version: '3.8'
networks:
  mbr_test_network_100:
    driver: bridge
    external: true
    # ipam:
      # config:
      #     - subnet: "172.24.100.0/16"
services:
  node_100:
    privileged: true
    networks:
      mbr_test_network_100:
        ipv4_address: "172.24.100.4"

    restart: unless-stopped
    image: massbit/massbitroute_node:v0.1.0
    command: "-n"
    # build:
    #   context: /massbit/massbitroute/app/src/sites/services/node
    #   dockerfile: install/mbr/build/node/Dockerfile.dev
    #   args:
    #     VERSION: 0.0.1-shamu-dev
    #     BRANCH: shamu
    container_name: mbr_node_100
    volumes:
      - ./node/logs:/massbit/massbitroute/app/src/sites/services/node/logs:rw
    environment:
      - MBR_ENV=v0.1.0
      - DOMAIN=massbitroute.net
      - PORTAL_URL=http://portal.massbitroute.net
      - INSTALL_CMD=http://portal.massbitroute.net/api/v1/node_install?id=9a01e782-e0a0-472f-b8d4-c704bca21f59&user_id=b1cf032d-5971-410a-90fe-9c454a4173f0&blockchain=eth&network=mainnet&zone=AS&data_url=http://34.81.232.186:8545&app_key=zAhrVEEyeCE3M7zEwU1cQA&portal_url=http://portal.massbitroute.net&env=shamu
    extra_hosts:
      - "hostmaster.massbitroute.net:172.24.100.254"
      - "ns1.massbitroute.net:172.24.100.254"
      - "ns2.massbitroute.net:172.24.100.254"
      - "api.massbitroute.net:172.24.100.254"
      - "stat.mbr.massbitroute.net:172.24.100.254"
      - "monitor.mbr.massbitroute.net:172.24.100.254"
      - "chain.massbitroute.net:172.24.100.205"
      - "portal.massbitroute.net:172.24.100.254"
      - "admin-api.massbitroute.net:172.24.100.254"
      - "dapi.massbitroute.net:172.24.100.254"
      - "scheduler.fisherman.massbitroute.net:172.24.100.254"
      - "gateway-dot-mainnet.monitor.mbr.massbitroute.net:172.24.100.209"
      - "gateway-eth-mainnet.monitor.mbr.massbitroute.net:172.24.100.209"
      - "node-eth-mainnet.monitor.mbr.massbitroute.net:172.24.100.209"
      - "node-dot-mainnet.monitor.mbr.massbitroute.net:172.24.100.209"
      - "node-eth-mainnet.stat.mbr.massbitroute.net:172.24.100.208"
      - "node-dot-mainnet.stat.mbr.massbitroute.net:172.24.100.208"
      - "gateway-eth-mainnet.stat.mbr.massbitroute.net:172.24.100.208"
      - "gateway-dot-mainnet.stat.mbr.massbitroute.net:172.24.100.208"
      - "api.ipapi.com:172.24.100.254"
      - "staking.massbitroute.net:172.24.100.254"
      - "ipv4.icanhazip.com:172.24.100.254"
